services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3360
    expose:
      - 3306
    volumes:
      - portfolio-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: portfolio

volumes:
  portfolio-mysql-data:
