services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - portfolio-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: portfolio

  api:
    build: ./api
    restart: always
    ports: 
      - 8080:8080
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: portfolio
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql

volumes:
  portfolio-mysql-data:
